name: PipelineWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: windows-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/Pipeline@v1
          with:
            azure-devops-project-url: https://dev.azure.com/okoraforpromise/AgileProject
            azure-pipeline-name: 'Webapp (1)'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN}}

        